- name: Create RabbitMQ docker container
  ansible.builtin.docker_container:
    name: rabbitmq
    image: rabbitmq:3-management
    state: started
    restart_policy: always
    ports:
      - "5672:5672"
      - "15672:15672"
    env:
      RABBITMQ_DEFAULT_USER: "{{ rabbitmq_user }}"
      RABBITMQ_DEFAULT_PASS: "{{ rabbitmq_password }}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
- name: Ensure Docker volume for RabbitMQ exists
  ansible.builtin.docker_volume:
    name: rabbitmq_data